# Site settings
permalink: "/:title"
timezone: America/Los_Angeles
baseurl: ""
url: "http://craigmaslowski.github.io"

title: Craig Maslowski - Software Engineer
email: craig@craigmaslowski.com
description: > # this means to ignore newlines until "baseurl:"
  Website for Craig Maslowski, Software Engineer, specializing in front end 
  web development with html5, css3, backbone, angular, less, and sass. 
  Full stack experience with node.js, express, meteor, and asp.net.
twitter_username: craig_maslowski
github_username:  craigmaslowski

# Build settings
markdown: kramdown
